sudo: false
language: cpp
compiler:
  - gcc-6
  - gcc-7
  - gcc-8
  - gcc-9
  - clang-6
  - clang-7
  - clang-8
  - clang-9
script:
  - cmake -DCMAKE_BUILD_TYPE=Debug .
  - make tests -j4
  - ./tests
